apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace-dev.yaml
namespace: project3-dev
patchesStrategicMerge:
  - ingress-dev-patch.yaml
images:
  - name: project1-nginx
    newName: 349821334974.dkr.ecr.us-east-1.amazonaws.com/project1-nginx
    newTag: cfddcc0d4c2a5798f529485c3b1cc575a82a791c
